DisplayName = "Tech"
Games = ["TMNF", "TMUF"]

TmxGame = "TMNF"
AutoSkipMode = "Finished"

[TmxQuery]
# "tag", not "primarytype" - see short_lol_tmnf.toml for why. 7=Tech, 8=SpeedTech
tag = "7,8"
inunlimiter = 0
routes = "0,2,3"
